language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - extra-google-m2repository
    - extra-android-m2repository
    - android-22
    - sys-img-armeabi-v7a-android-22
